import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "grkn.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-full flex justify-center" lang="en">
      <body className="h-full max-w-[90rem] flex flex-col   overflow-x-hidden md:px-20 sm:px-14 px-8 lg:px-24 text-white bg-[#121212] w-full">
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
